algorithm: 'carefl'  # in {'CAReFl', 'LRHyv', 'RECI', 'ANM'} OR in {'CAReFl', 'gp', 'linear'}
n_sims: 11

data:
  timeseries_idx: 0
  seed: 0
  lag: [1, 2, 3]


# only relevant for flows
flow:
  architecture: 'CL'
  net_class: 'MLP4'  # in {'MLP', 'ARMLP', 'MLP4'}.lower()
  nl: 4
  nh: 10
  batch_norm: false
  prior_dist: 'laplace'
  # for CL
  scale_base: false
  shift_base: false
  scale: true


training:
  epochs: 400
  verbose: false
  split: .8
  seed: 0
  batch_size: 32


optim:
  weight_decay: 0.000
  optimizer: "Adam"
  lr: 0.001
  beta1: 0.9
  amsgrad: false
  scheduler: true


